### ISSUE TITLE
problem with fabric-server [1.16.4]

### ISSUE THREAD

**Issue by Muglegack** [Pepperoni-Jabroni/MapAtlases#1]
attached a log. For further needed information, feel free to ask. :)
I have fabric, api and some other mods installed.
Works in Singleplayer; great mod!
[latest.log](https://github.com/Pepperoni-Jabroni/MapAtlases/files/5861367/latest.log)

**Comment by Pepperoni-Jabroni** [comment]
Thanks @Muglegack for reporting & providing a log! This was fixed with a number of commits & has been published to both Release and Curseforge!
