### ISSUE TITLE
Reposition the HUD minimap

### ISSUE THREAD

**Issue by FewerFlaws** [Pepperoni-Jabroni/MapAtlases#10]
I'd like to request the ability to, through config, adjust the position of the HUD minimap.  Ideally I could select the corner it anchors to then add vertical and horizontal offsets.  Pixel offsets are fine.  Relative offsets are better (a floating point between 0 and 1 which calculates the offset as a percentage of screen height/length).

**Comment by Pepperoni-Jabroni** [comment]
This is complete for v1.3.1. Thanks for your suggestion!
