### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by BluePixel1708** [Pepperoni-Jabroni/MapAtlases#11]
I'm playing modded and wanted to use map atlases for tha vanilla style maps but the game crashes on launch
[crash-2021-02-11_16.35.41-client.txt](https://github.com/Pepperoni-Jabroni/MapAtlases/files/5968869/crash-2021-02-11_16.35.41-client.txt)

**Comment by Pepperoni-Jabroni** [comment]
Please update your Fabric API version to 0.30.0 (https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/3183643). It's marked as "1.16.5" but works fine in "1.16.3". Version 0.25.0, which is what you're using, is missing a Fabric API library this mod uses (the library being "ServerPlayConnectionEvents").
