### ISSUE TITLE
Crash with 1.2.5 Version

### ISSUE THREAD

**Issue by Blaueschmied** [Pepperoni-Jabroni/MapAtlases#12]
Hi, I have a little problem with your newest version of this mod!
It simply crashes on load.

[crash-2021-03-05_09.10.54-client.txt](https://github.com/Pepperoni-Jabroni/MapAtlases/files/6089072/crash-2021-03-05_09.10.54-client.txt)

**Comment by Pepperoni-Jabroni** [comment]
Thanks for reporting & including log! Will address this later this evening.

**Comment by Pepperoni-Jabroni** [comment]
@Blaueschmied, can you try installing [Cloth Config API](https://www.curseforge.com/minecraft/mc-mods/cloth-config/files/3210410)?

**Comment by Tajnymag** [comment]
Had the same crash as @Blaueschmied. Cloth Config fixed it.

**Comment by Pepperoni-Jabroni** [comment]
Thanks for confirming @Tajnymag - closing this issue out.
