### ISSUE TITLE
Add config option to override right click HUD size

### ISSUE THREAD

**Issue by HerrahStrings** [Pepperoni-Jabroni/MapAtlases#16]
There's a configuration option to override the size of the minimap on the hud, but no option to override the size of the map when the atlas is right-clicked

![image](https://user-images.githubusercontent.com/55819817/117563317-664aa000-b0e8-11eb-8c21-a2f6ac710020.png)

as the map can be zoomed out and scrolled, this would be very useful, especially for higher resolution displays.

**Comment by Pepperoni-Jabroni** [comment]
Thank you for the recommendation, this is a great request!

**Comment by Pepperoni-Jabroni** [comment]
This is complete for v1.3.1. Thanks for the suggestion!
