### ISSUE TITLE
1.17

### ISSUE THREAD

**Issue by supersaiyansubtlety** [Pepperoni-Jabroni/MapAtlases#17]
Do you plan to update this mod for 1.17?

**Comment by Pepperoni-Jabroni** [comment]
Yes, I do. But the map-related code has changed a bit in 1.17, so I'll need to find time to figure out how to update the mod. There's some things I'd like to improve about it as well, if possible. You'll see activity on this repo increase whenever an update is imminent, so feel free to "Star" to keep updated.
