### ISSUE TITLE
Atlas can't be made in the end even though normal maps work

### ISSUE THREAD

**Issue by Skel20071** [Pepperoni-Jabroni/MapAtlases#19]
When I try to make a map atlas with a end map it doesn't work. It works in the overworld, but not the end. I'm not sure whether this is the mod on its own or it's incompatible with another mod. I would like it of you could see what's wrong and maybe fix it. Keep up the good work!

**Comment by Pepperoni-Jabroni** [comment]
This has to do with the fact that Dimensions aren't actually stored on the Map's internal data or stored on the Client side. As a result, map adding is a best-effort thing right now. I'll dig a bit and see if I can resolve this issue. Thanks for reporting on GH!

**Comment by Pepperoni-Jabroni** [comment]
This has since been resolved as of my latest testing. Closing this out. Thanks for reporting!
