### ISSUE TITLE
[Request] configs to nerf

### ISSUE THREAD

**Issue by supersaiyansubtlety** [Pepperoni-Jabroni/MapAtlases#2]
I'd like to be able to configure MapAtlases so that it acts as nothing more than a nice collection of your maps. 

Specifically I'd like to disable the atlas' ability to fill out maps, and to disable the recipe that lets you combine the atlas with an empty map.

**Comment by Pepperoni-Jabroni** [comment]
Thanks @supersaiyansubtlety for the suggestion! This has been committed in revision 44c970e41c9 & built into V1.2.1, submitted to Releases & Curseforge. Enjoy!

**Comment by supersaiyansubtlety** [comment]
Thanks!
