### ISSUE TITLE
Mini-map frozen when Atlas item is in INVENTORY with proper option enabled

### ISSUE THREAD

**Issue by rbdej** [Pepperoni-Jabroni/MapAtlases#21]
I saw that there's an option where you could enable the mini-map to show even if you placed the Atlas item in the player Inventory aside from the player Hotbar but the Mini-map is frozen when this option is enabled.

**Comment by Pepperoni-Jabroni** [comment]
Hmm I was unable to repro this with local testing. Will dig a bit further and let you know what I find. Thank you for reporting!

**Comment by Pepperoni-Jabroni** [comment]
Closing as this has gone stale & I was unable to repro. Please report again if you're still experiencing this issue. Thanks!
