### ISSUE TITLE
Crash on first use, but fine after restart (Log)

### ISSUE THREAD

**Issue by skylorbeck** [Pepperoni-Jabroni/MapAtlases#22]
[crash-2021-12-26_11.13.59-client.txt](https://github.com/Pepperoni-Jabroni/MapAtlases/files/7780626/crash-2021-12-26_11.13.59-client.txt)
I was playing in LAN mode at the time. No problems since.

**Comment by Pepperoni-Jabroni** [comment]
The Screen function no longer relies on this data, so this is resolved. Thanks for reporting!
