### ISSUE TITLE
i got connection timed out in a singleplayer world after crafting the atlas

### ISSUE THREAD

**Issue by julsaci** [Pepperoni-Jabroni/MapAtlases#28]

**Comment by DumCactus** [comment]
i accidentally used my sisters account in making this, im having this problem.
i cant really put a log since it didnt crash, it just times me out from my singleplayer offline world

**Comment by DumCactus** [comment]
ill put it here anyway
[latest.log](https://github.com/Pepperoni-Jabroni/MapAtlases/files/8735168/latest.log)

**Comment by Pepperoni-Jabroni** [comment]
Thanks for the report! Will take a look when I get the chance.

**Comment by Pepperoni-Jabroni** [comment]
I added a try/catch in mapAtlasClientSync which will stop the client from crashing. Thanks for reporting!
