### ISSUE TITLE
[Feature request] Lil nerf.

### ISSUE THREAD

**Issue by RDKRACZ** [Pepperoni-Jabroni/MapAtlases#3]
Firstly, thank you for giving us a non-op minimap mod.
Features I would like:
Fill an empty map in the atlas only when it is off-hand and not when in the hotbar, like a vanilla empty map.
Show a minimap only when an atlas is off-hand and not when in the hotbar.

**Comment by RDKRACZ** [comment]
Also, you can open a minimap by M key but not close it.

**Comment by RDKRACZ** [comment]
I saw the mod icon on the curseforge but you forgot to replace fabric placeholder in the jar.

**Comment by RDKRACZ** [comment]
And the minimap will cover potions icons in the right corner, maybe it should move icons to the left of the map?

**Comment by RDKRACZ** [comment]
The minimap should hide when opening f3 so it won't cover some info

**Comment by Pepperoni-Jabroni** [comment]
I opened Issue #7 to reflect the GUI-related issues of potion effects & F3.

The Atlas is selected when the hotkey to open it is pressed, so it does force players to hold it when they open the GUI.

However, I will add a Config toggle to force players to hold an Atlas in order for it to update or draw the mini-map.

**Comment by Pepperoni-Jabroni** [comment]
Added Config option to force players to hold their Atlas in main/off hands in order for it to function, this was addressed in revision 483630494 & built into V1.2.3.
