### ISSUE TITLE
Create Fabric crash on using empty map

### ISSUE THREAD

**Issue by WarmIceCream** [Pepperoni-Jabroni/MapAtlases#30]
Seems to have a conflict with Create Fabric, where when I have both mods installed and try to use an empty map, the game crashes (and whenever I try to rejoin that world, the game crashes again)

using the latest versions of all mods for mc 1.18.2
[crash-2022-06-12_22.58.44-client.txt](https://github.com/Pepperoni-Jabroni/MapAtlases/files/8893825/crash-2022-06-12_22.58.44-client.txt)

**Comment by cfnnit** [comment]
same here. 

https://pastebin.com/QLQ7ppax

**Comment by ivan-work** [comment]
bump, same here. Deleting the "corrupted" map on server world also helps.

https://paste.ee/p/R1fcH

**Comment by seylerius** [comment]
Hi there. I've also been struggling with this crash, and have narrowed the issue down to a conflict with Create. I created a PolyMC instance of 1.18.2 with the following mods:
- **Cloth Config**: `6.2.62`
- **Create**: `mc1.18.2_v0.4.1+637`
- **Fabric API**: `0.57.0+1.18.2`
- **Map Atlases**: `1.3.3`
- **ModMenu**: `3.2.3`

With Map Atlases disabled, no crash. With Create disabled, no crash. With both enabled, it crashes as shown in the linked log below.

https://mclo.gs/G8haMKe
