### ISSUE TITLE
Crash with MemoryLeakFix (I think?)

### ISSUE THREAD

**Issue by saintsareprey** [Pepperoni-Jabroni/MapAtlases#31]
Additional info:
fabric loader 0.14.7 - 1.18.2
fabric api 0.56.0

here's the crash log: https://gist.github.com/AndyXTJ/c840a5ee3b53e066fea713b89d06e763

**Comment by Pepperoni-Jabroni** [comment]
Thanks for the report! Looks like the crash log is 404'ing?

**Comment by saintsareprey** [comment]
Oh damn, just a sec

**Comment by saintsareprey** [comment]
https://gist.github.com/saintsareprey/0cccd573ab8388fbaf532e660909e32b let's see if this works now lmao, maybe me changing my profile messed up the link

**Comment by Pepperoni-Jabroni** [comment]
This is an incompatibility with Create Fabric which has since been addressed. Thanks for reporting!
