### ISSUE TITLE
crash on using empty map

### ISSUE THREAD

**Issue by cfnnit** [Pepperoni-Jabroni/MapAtlases#32]
Client crash continue until the dropping the map externally
I love this mods because other map mods are too overpowered 

[crash-2022-06-18_08.52.43-client.txt](https://github.com/Pepperoni-Jabroni/MapAtlases/files/8931839/crash-2022-06-18_08.52.43-client.txt)

**Comment by Pepperoni-Jabroni** [comment]
Thanks for reporting! I'll make sure this is fixed in the new build I'm working on now.

**Comment by Pepperoni-Jabroni** [comment]
Most recent 1.18 build v2.0.1 should fix this. Thanks for reporting!
