### ISSUE TITLE
Error when opening a page in "REI"

### ISSUE THREAD

**Issue by RepkinTIM** [Pepperoni-Jabroni/MapAtlases#49]
As I understand it, this is due to the fact that "RoughlyEnoughItems" cannot show some item from the Map Atlas mod. Or did I do something wrong?

Error Log - https://paste.ee/p/GbiuG

**Comment by RepkinTIM** [comment]
But perhaps this is due to a conflict with some other mod. I have 145+ more, lol)

**Comment by Pepperoni-Jabroni** [comment]
Going to fold this into #50 as a duplicate. Thank you for reporting!
