### ISSUE TITLE
Mini-map don't show up only in multiplayer mode until page flipping 

### ISSUE THREAD

**Issue by jjjbaku** [Pepperoni-Jabroni/MapAtlases#58]
After page flipping no matter how many times I quit and join the server the mini-map remains. After that it can only be reproduced when I close the game and launch again.
This problem doesn't exist in single player mode.

Mod version: 2.0.1
Game version: 1.18.2

Log: [log_220810.txt](https://github.com/Pepperoni-Jabroni/MapAtlases/files/9297802/log_220810.txt)

**Comment by Pepperoni-Jabroni** [comment]
I've confirmed a repro:
1. Run a server
2. Connect a client
3. Quit the client, restart, & rejoin server
4. See that no mini-map is drawn until a page turn occurs
