### ISSUE TITLE
[Suggestion] A pack of options to make the mod more customizable for modpack makers.

### ISSUE THREAD

**Issue by murao-kun** [Pepperoni-Jabroni/MapAtlases#60]
Hello! I am modpack maker of unreleased Unity Modpack, that will be build around of idea to keep vanilla mechanics and infuse mods into them without making vanilla features pointless.
Your mod fill my criteria perfectly. This mod is more expanding vanilla maps mechanics rather then making them pointless.

When I was forging your mod into my modpack I come up with some issues that stopping me from integrating it seamlessly.
First of all one of my ideas was to remade atlas UI by making the map x32 instead of x16.
Here the result of that: 
![image](https://user-images.githubusercontent.com/110398598/186460125-b1b62537-980b-41a5-beb5-452f92f4469f.png)
But here comes the thing that I do not want to happen, like vanilla maps being retextured to x32 too.
*First suggestion*
Make Atlas UI and other UI parts to have their own textures instead of using vanilla one.
For both UI render and right click on the Atlas action. (It will make possible to create minimap borders as well)

The second thing that you should resolve that opening Atlas UI making JEI/REI appear, that is totally pointless in there.
Here the example of what it is looking like:
![image](https://user-images.githubusercontent.com/110398598/186461110-44d490e5-c351-44f9-ad71-fd93dc0f6cff.png)
*Second suggestion*
Make JEI/REI compat for Atlas UI.

When I am having potion effect and it is displaying on UI, the minimap automaticly moving itself, but with my custom UI edits, it is not detecting there the actual effect box position is. (It is better to not detect it, but rather better to make additional config options for additional offset when potion effects are active)
Here the example of what it is looking like:
![image](https://user-images.githubusercontent.com/110398598/186462128-624f2d9a-b903-4317-bb76-e375ed8202fc.png)
*Third suggestion*
Make additional config values for minimap potions effect offset.

The last thing might be hard to add, but would be cool to have not only background to each UI element (map texture), but additionally foreground too.
Example of UIs that need that feature:
![image](https://user-images.githubusercontent.com/110398598/186462839-9003c5a4-e4ab-4119-af2b-b6caf650ab3b.png)
![image](https://user-images.githubusercontent.com/110398598/186462864-807f7340-0f21-49b2-9bd2-e2dafb03b1bd.png)
*Fourth suggestion*
Make foreground for Atlas and minimap UI for additional customization.

I hope that things are not that hard to add, and will greatly increase mod's customization that will be helpful for modpack makers. Thank you for amazing mod, hope to use it in my modpack and make a cool way to use maps again!

**Comment by Pepperoni-Jabroni** [comment]
Wow - this is probably the most detailed GH Issue I've ever received, thanks! Could you expand on your fourth request? What foreground elements are you envisioning?

**Comment by murao-kun** [comment]
Sure. :)
For now minimap and atlas UI is made by second layer, the first one - is background, map texture and the second one is map content, like terrain. I imagine an introduction of third layer - foreground, the overlay above everything. That will make possible to draw a border for minimap for example, without touching background texture, and as for atlas UI and foreground usage I can make visual example, but can't really explain it in text. (Not at PC right now, will have time to make it tomorrow to extend that suggestion)

**Comment by Pepperoni-Jabroni** [comment]
For your second suggestion, you can use Ctrl+O to hide REI/JEI. Does that solve the issue? Or do you know if those mods allow you to blocklist a certain Screen type?

For me to do this, I'd have to inject some new code to hide REI/JEI into both mods for whichever is loaded, which isn't very clean. I can still try it out if you like though.

**Comment by Pepperoni-Jabroni** [comment]
And for your fourth suggestion, are you just thinking of another square texture (no texture by default) that can be applied over the map textures?

**Comment by Pepperoni-Jabroni** [comment]
Suggestion 1 has been implemented in 762dfce030a36aaed60ee5458c433ba06110a627

**Comment by Pepperoni-Jabroni** [comment]
Suggestion 3 has been implemented in 48afe565ada72d17df6860b98350a5d800f110ff

**Comment by murao-kun** [comment]
> For your second suggestion, you can use Ctrl+O to hide REI/JEI. Does that solve the issue? Or do you know if those mods allow you to blocklist a certain Screen type?
> 
> For me to do this, I'd have to inject some new code to hide REI/JEI into both mods for whichever is loaded, which isn't very clean. I can still try it out if you like though.

Checked JEI and there is no option to blacklist seems like. As for REI I do not really know.

**Comment by murao-kun** [comment]
> And for your fourth suggestion, are you just thinking of another square texture (no texture by default) that can be applied over the map textures?

Yep, exactly like that and if it is possible adding another one for regular maps could be helpful and useful too.

**Comment by Pepperoni-Jabroni** [comment]
Suggestion 4 has been implemented in 21db570ba85f22e390b8c699cf6f1db1b256e829

**Comment by murao-kun** [comment]
Thank you! You are doing amazing job!

**Comment by Pepperoni-Jabroni** [comment]
Just to let you know, I probably won't look into auto-hiding REI/JEI too soon. But the new version 2.1.0 contains your other 3 suggestions! Thanks again for submitting your suggestions!

**Comment by murao-kun** [comment]
Thank you for implementing them! I will share the results and look for other methods that could help you hide JEI/REI in easier way. Thank you once again! :)

**Comment by Pepperoni-Jabroni** [comment]
I'm going to close out this enhancement and fold the remaining request for REI/JEI hiding into Issue #66. Thanks again for submitting your requests! And please let me know if there's anything else I can to or if you find any issues. Thanks!

**Comment by murao-kun** [comment]
Thank you a lot!
