### ISSUE TITLE
[1.19.2 Forge] Shear Durability/Map Removal

### ISSUE THREAD

**Issue by HalcyonSeas73** [Pepperoni-Jabroni/MapAtlases#62]
Map Atlas version: 3.0.1
Forge version: 43.1.1
Minecraft version: 1.19.2

When shift+clicking to remove maps en-masse, Shear durability goes into the negatives, rather than stopping at a durability of zero.
Additionally, all maps removed are 'blank', labelled as "Unknown Map"

![image](https://user-images.githubusercontent.com/84727791/186503147-acc47ab4-7be0-4304-9d61-26355750fb47.png)

![image](https://user-images.githubusercontent.com/84727791/186503261-abe03e06-bcf2-4e28-a1b4-2a5e5887e6ae.png)

**Comment by Pepperoni-Jabroni** [comment]
Even though this is for the Forge version, since they're highly related, I assume this will repro in the Fabric version as well. Will take a look. Thanks for reporting!
