### ISSUE TITLE
Crash when use map atlases

### ISSUE THREAD

**Issue by cfnnit** [Pepperoni-Jabroni/MapAtlases#63]
https://pastebin.com/mPFK1TMP

I made map atlases with expand map that [three times](https://media.discordapp.net/attachments/680243913868705793/1013484100323115080/unknown.png)

**Comment by Pepperoni-Jabroni** [comment]
This appears to be specific to the Forge port of the mod. Can you comment this on the Forge version's Curseforge page as well? The stack trace doesn't look reproducible on the Fabric version (which is what this repo is).

**Comment by Monster-Zer0** [comment]
https://aofpaste.com/vuxugosupu.yaml same issue.

https://github.com/Pepperoni-Jabroni/MapAtlases/blob/3491c94fae73867bbd3b3421ef03659443e0fdc7/src/main/java/pepjebs/mapatlases/utils/MapAtlasesAccessUtils.java#L82

Atlas tried getting items from the inventory, and one of the stacks had a null in its items... somehow

**Comment by Pepperoni-Jabroni** [comment]
Interesting... will push a new version to protect against this soon.

**Comment by Pepperoni-Jabroni** [comment]
So your crash @Monster-Zer0 is actually different from the one @cfnnit has reported here. Additionally, you've reported the Fabric version and they've reported the Forge version. I'm going to fork your crash into a new Issue - #67.

**Comment by Pepperoni-Jabroni** [comment]
@cfnnit your version of Map Atlases (v2.1.0 on Forge) is outdated. Please ask Lily to port the latest version to 1.18.2 on the [Curseforge page for the Forge version](https://www.curseforge.com/minecraft/mc-mods/map-atlases-forge)
