### ISSUE TITLE
Server Crash on Boat

### ISSUE THREAD

**Issue by lanwoodall423** [Pepperoni-Jabroni/MapAtlases#72]
Two players in server boating on existing chunks with atlases in inventory

`---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2022-09-30 21:27:52
Description: Exception in server tick loop

java.util.ConcurrentModificationException
	at Not Enough Crashes deobfuscated stack trace.(1.19.2+build.9)
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1597)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1620)
	at pepjebs.mapatlases.lifecycle.MapAtlasesServerLifecycleEvents.mapAtlasServerTick(MapAtlasesServerLifecycleEvents.java:149)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$0(ServerTickEvents.java:40)
	at net.minecraft.server.MinecraftServer.handler$ckl000$onStartTick(MinecraftServer:7316)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:819)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:257)
	at java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Linux (amd64) version 5.4.0-109-generic
	Java Version: 17.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1823169976 bytes (1738 MiB) / 5368709120 bytes (5120 MiB) up to 5368709120 bytes (5120 MiB)
	CPUs: 32
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz
	Identifier: Intel64 Family 6 Model 63 Stepping 2
	Microarchitecture: Haswell (Server)
	Frequency (GHz): 3.20
	Number of physical packages: 2
	Number of physical CPUs: 16
	Number of logical CPUs: 32
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 178078.59
	Virtual memory used (MB): 245953.61
	Swap memory total (MB): 49151.99
	Swap memory used (MB): 12957.48
	JVM Flags: 2 total; -Xmx5120M -Xms512M
	Fabric Mods: 
		additionaladditions: Additional Additions 5.0.2
		advanced_runtime_resource_pack: Runtime Resource Pack 0.6.4
		adventurez: AdventureZ 1.4.16
		almostunified: AlmostUnified 0.1.1
		alternate-current: Alternate Current 1.4.0
		amethyst_imbuement: Amethyst Imbuement 1.19-13
			amethyst_core: Amethyst Core 0.3.2+1.19
			coloredglowlib: ColoredGlow Lib 1.3.4
			structurized-reborn: Structurized Reborn 1.19-01
		architectury: Architectury 6.2.46
		armorstatues: Armor Statues 4.0.0
		artifacts: Artifacts 7.1.1+fabric
			expandability: ExpandAbility 6.0.0
			step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		attributefix: AttributeFix 17.1.2
		balm-fabric: Balm 4.5.2+0
		bambooeverything: Bamboo Everything 2.0.0-build.23+mc1.19.2
		bclib: BCLib 2.1.0
		betteranimalsplus: Better Animals Plus 1.19-11.0.7
		bettercombat: Better Combat 1.4.3+1.19
		betterdeserttemples: YUNG's Better Desert Temples 1.19.2-Fabric-2.1.1
		betterdungeons: YUNG's Better Dungeons 1.19.2-Fabric-3.1.1
		bettermineshafts: YUNG's Better Mineshafts 1.19.2-Fabric-3.1.2
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.19.2-Fabric-2.0
		betterstrongholds: YUNG's Better Strongholds 1.19.2-Fabric-3.1.2
		bettertridents: Better Tridents 4.0.1
		betterwitchhuts: YUNG's Better Witch Huts 1.19.2-Fabric-2.0.1
		bewitchment: Bewitchment 1.19-5
			impersonate: Impersonate 2.7.0
		biomemakeover: Biome Makeover 1.19.2-1.5.12
		blockrunner: Block Runner 4.2.0
		boat-with-everything: Boat with Everything 1.1.0
		bookshelf: Bookshelf 16.1.5
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.4.2-1.19
			maelstrom_library: Maelstrom Library 1.3-1.19-pre1
			multipart_entities: MultipartEntities 1.2-1.19-pre1
		brewery: Brewery 0.1.0+1.19.2
			hologram-api: Hologram API 0.2.2+1.19
			more_codecs: More Codecs 0.2.2+1.18
			net_objecthunter_exp4j: exp4j 0.4.8
			polymer: Polymer (Core) 0.2.16+1.19.2
				packet_tweaker: Packet Tweaker 0.3.0+1.18.2
				polymer-registry-sync-manipulator: Polymer Registry Sync Manipulator 0.0.3+1.19.2
			server_translations_api: Server Translations API 1.4.17+1.19.2
			sgui: sgui 1.1.5+1.19.1
		bwplus: Bewitchment Plus 1.19-5
			terraform-wood-api-v1: Terraform Wood API (v1) 4.1.1
		byg: Oh The Biomes You'll Go 2.0.0.11
		cardinal-components: Cardinal Components API 5.0.2
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-block: Cardinal Components API (blocks) 5.0.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			cardinal-components-item: Cardinal Components API (items) 5.0.2
			cardinal-components-level: Cardinal Components API (world saves) 5.0.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.2
			cardinal-components-world: Cardinal Components API (worlds) 5.0.2
		carrier: Carrier 1.11.0
		charm: Charm 4.4.4
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 9.0.0+11
		collective-fabric: Collective (Fabric) 4.70
		combatroll: Combat Roll 1.0.7+1.19
		connectiblechains: Connectible Chains 2.1.3+1.19.2
		cosmetic-armor: Cosmetic Armor 1.4.0
		creativecore: CreativeCore (Fabric) 2.8.5
		creaturesofthesnow: Creatures Of The Snow 3.1.0+1.19.2
		creeperoverhaul: Creeper Overhaul 2.0.3
		damagetilt: Damage Tilt 1.19-fabric-0.1.2
		dawn: Dawn API 3.5.0
		debugify: Debugify 2.7.1
			com_github_llamalad7_mixinextras: mixinextras 0.0.12
		deeperdarker: Deeper And Darker 1.0.2b-fabric
			customportalapi: Custom Portal Api 0.0.1-beta52-1.19
		diagonalfences: Diagonal Fences 4.2.1
		dimdoors: DimensionalDoors 5.0.0
			com_flowpowered_flow-math: flow-math 1.0.3
			com_github_dimensionaldevelopment_poly2tri_java: poly2tri.java 0.1.1
			matrix: Matrix 1.0.0
			org_jgrapht_jgrapht-core: jgrapht-core 1.1.0
		discholder: Kenza's Disc Holder and DJ 1.3.0
			kirin: Kirin UI 1.11.0
			libgui: LibGui 6.0.1+1.19
				jankson: Jankson 4.1.1+j1.2.1
				libninepatch: LibNinePatch 1.1.0
		doodads: Doodads 0.1.2-1.19.2
		dynmap: Dynmap 3.4
		earthtojavamobs: Earth2Java 1.9.3
		easyanvils: Easy Anvils 4.0.0
		ecologics: Ecologics 2.1.10
		elden_horses: Elden Horses 1.0.1+1.19.2
		emotecraft: Emotecraft 2.2.5
		everycomp: Every Compat 1.19.2-2.0.4
		expandeddelight: Expanded Delight 0.2.2
		expert_armor: Expert_Armor 2.1.6
		fabric-api: Fabric API 0.62.0+1.19.2
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.10+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.18+c6af733c90
			fabric-command-api-v1: Fabric Command API (v1) 1.2.12+f71b366f90
			fabric-commands-v0: Fabric Commands (v0) 0.2.29+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.35+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.3.1+624e468e90
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.2+93d8cb8290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.6+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.2.0+b598f4ac90
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.32+0dd10df690
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.19+9ff28f4090
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.29+c6af733c90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.29+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.22+c6af733c90
			fabric-item-api-v1: Fabric Item API (v1) 1.5.8+93d8cb8290
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.30+93d8cb8290
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.4+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.7+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.4+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.15+33fbc73890
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.5+c6af733c90
			fabric-networking-v0: Fabric Networking (v0) 0.3.22+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.12+93d8cb8290
			fabric-particles-v1: Fabric Particles (v1) 1.0.11+79adfe0a90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.26+c6af733c90
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.15+aeb40ebe90
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.8+c6af733c90
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.12+a29562c890
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.7.0+93d8cb8290
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.1+1cc24b1b90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.1+93d8cb8290
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.1+42d99c3290
		fabric-language-kotlin: Fabric Language Kotlin 1.8.3+kotlin.1.7.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.3
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.0
		fabricloader: Fabric Loader 0.14.9
		fallingtree: FallingTree 3.10.0
		farmersdelight: Farmer's Delight 1.19-1.3.3
		farmersknives: Farmer's Knives 2.1
		fastload: Fast Load 1.2.0
		ferritecore: FerriteCore 4.2.1
		forgeconfigapiport: Forge Config API Port 4.2.6
		friendsandfoes: Friends&Foes 1.5.10
		geckolib3: Geckolib 3.1.20
			com_eliotlash_mclib_mclib: mclib 19
			com_eliotlash_molang_molang: molang 19
		geodes: More Geodes 1.5.1
		glow_ink_plus: Glow Ink Plus Mod 1.0.2-1.19.x
		go-fish: Go Fish 1.6.0-1.19.1
		goodall: Goodall 1.1.1
		horsestatsvanilla: Horse Stats Vanilla 4.2.2
		iceberg: Iceberg 1.0.46
		immersive_paintings: Immersive Paintings 0.2.0+1.19.2
		impaled: Impaled 1.1.4
		incendium: Incendium + Seed Fix 5.1.0
		infinitybuttons: Infinity Buttons 1.5.0-mc1.19
		interactic: Interactic 0.1.11+1.19
		java: Java HotSpot(TM) 64-Bit Server VM 17
		kofitable: Kofi Table 1.0.4+1.19.x
		krypton: Krypton 0.2.1
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		lazydfu: LazyDFU 0.1.3
		letmedespawn: Let Me Despawn fabric-1.0.2
		lithium: Lithium 0.8.3
		lovely_snails: Lovely Snails 1.1.0+1.19
		map_atlases: Map Atlases 2.1.0
		mcwbridges: Macaw's Bridges 2.0.4
		mcwfences: Macaw's Fences and Walls 1.0.6
		mcwlights: Macaw's Lights and Lamps 1.0.4
		mcwpaintings: Macaw's Paintings 1.0.4
		mcwpaths: Macaw's Paths and Pavings 1.0.1
		mcwtrpdoors: Macaw's Trapdoors 1.0.7
		medievalweapons: Medieval Weapons 1.4.0
		megaparrot: Megaparrot 1.0.6
		midnightlib: MidnightLib 0.6.1
		minecraft: Minecraft 1.19.2
		minelib: mine11lib 0.1.3+1.19
			com_sksamuel_scrimage_scrimage-core: scrimage-core 4.0.31
		mixintrace: MixinTrace 1.1.1+1.17
		mob_catcher: Mob Catcher 1.2.11
		mobscarecrow: Mob Scarecrow 2.2.1-1.19.1
		moonlight: Moonlight 1.19.2-2.0.29
		more-axolotls: More Axolotls 1.0.2
		more_babies: More Babies 1.0.0
		more_ladders: More Ladders fabric-1.0.1-1.19.2
		morediscs: More Music Discs 1.19.2-20
		morefrogs: More Frogs 1.19.x-1.2.3-fabric
		morevillagers: More Villagers 4.0.2
		naturalist: Naturalist 2.1.1
		nbtcrafting: NBT Crafting 2.2.0+mc1.19
		notenoughcrashes: Not Enough Crashes 4.1.8+1.19.2
		nox: Nox 2.0.0
		npcvariety: NPC Variety 2.2.2
		nullscape: Nullscape 1.2
		owo: oωo 0.8.2+1.19
			blue_endless_jankson: jankson 1.2.1
		patchouli: Patchouli 1.19.2-76-FABRIC
			fiber: fiber 0.23.0-2
		peculiarpieces: Peculiar Pieces 1.2.13+1.19.x
			playerabilitylib: Pal 1.6.0
			reach-entity-attributes: Reach Entity Attributes 2.3.0
		pehkui: Pehkui 3.4.2+1.14.4-1.19.2
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		philips_ruins__fabric: Philips ruins 1.19.2 fabric 1.6.2
		pickyourpoison: Pick Your Poison 1.0.9
			org_json_json: json 20211205
		player-animator: Player Animator 0.3.5
		probablychests: Probably Chests 0.5.4-1.19.1
		puzzleslib: Puzzles Lib 4.3.8
		qu-enchantments: Qu Enchantments 1.2.4-1.19
			mm: Manningham Mills 2.3
		repurposed_structures: Repurposed Structures 6.1.1+1.19
		revelationary: Revelationary 1.0.2
		rocks: This Rocks! 1.6.1
		roughly_enough_loot_tables: Roughly Enough Loot Tables 1.19-1.0
		roughlyenoughitems: Roughly Enough Items 9.1.550
			error_notifier: Error Notifier 1.0.9
		roughlyenoughprofessions: Roughly Enough Professions 1.1.2
		roughlyenoughresources: Roughly Enough Resources 2.6.0
		servercore: ServerCore 1.3.2-1.19.2
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
			fabric-api-base: Fabric API Base 0.4.12+93d8cb8290
			fabric-command-api-v2: Fabric Command API (v2) 2.1.8+93d8cb8290
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.0+33ffe9ec90
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			me_lucko_spark-api: spark-api 0.1-SNAPSHOT
			placeholder-api: Placeholder API 2.0.0-beta.7+1.19
		silencemobs-fabric: Silence Mobs (Fabric) 2.6
		simple_shields: Simple Shields Mod 1.0.0 - 1.19
		skylorlib: SkyLib 1.5.1
		smoothboot: Smooth Boot 1.19-1.7.1
		soulfired: Soul fire'd 1.1.0.0
		spark: spark 1.9.40
		starlight: Starlight 1.1.1+fabric.ae22326
		steves_vanilla: Steves Vanilla 1.19.2+2.0.1
		stoneholm: Stoneholm 1.4.4
		strawgolem: Straw Golem 2.0.0b2
		structory: Structory 1.0.1
		supplementaries: Supplementaries 1.19.2-2.2.3
		t_and_t: Towns and Towers - Structure Add-on 1.8.2
		tenshilib: TenshiLib 1.19-1.6.10
		terrablender: TerraBlender 2.0.1.127
		terralith: Terralith 2.3
		the_bumblezone: The Bumblezone - Fabric 6.1.13+1.19.2
			fake-player-api: Fake Player API 0.4.0
		themissingvillages: BigReefer's The Missing Villages Mod 2.0.0
		things: Things 0.2.20+1.19
		transparent: Transparent 5.1.0
		transportables: Transportables 1.2.1
		trashslot: TrashSlot 12.0.1
		trinkets: Trinkets 3.4.0
		universal_ores: Universal Ores 1.4.2
		untitledduckmod: Untitled Duck Mod 0.6.1
		variant_bookshelves: Variant Bookshelves 1.1.9
		variant_grindstones: Variant Grindstones 1.0.9
		variantbarrels: Variant Barrels 2.2
		variantcomposters: Variant Composters 1.0.4
		variantcraftingtables: Variant Crafting Tables 3.2.6
		visiblebarriers: Visible Barriers 1.5.3+1.19.x
		visualworkbench: Visual Workbench 4.2.0
		voidz: VoidZ 1.0.9
		vsas: Variant Sticks and Stuff 2.1.6
		weaponmaster: YDM's Weapon Master 3.0.2
		wilderwild: Wilder Wild 1.1.0
			frozenblocklib: FrozenBlock's Library 1.1-Fabric+1.19.2-unstable
		windchimes: Windchimes 1.2.1
		xps: Xp Obelisk 0.4.6-r+1.19.2-Fabric
		xtraarrows: Xtra Arrows 2.0
		yungsapi: YUNG's API 1.19.2-Fabric-3.6.1
		yungsbridges: YUNG's Bridges 1.19.2-Fabric-3.0.1
		yungsextras: YUNG's Extras 1.19.2-Fabric-3.0.1
	Server Running: true
	Player Count: 0 / 60; []
	Data Packs: vanilla, Fabric Mods, dimdoors/classic (incompatible), dimdoors/default (incompatible), Everycomp Generated Pack, expert_armor/eamodcompat, Supplementaries Generated Pack
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
	Suspected Mods: Map Atlases (map_atlases)`

**Comment by Pepperoni-Jabroni** [comment]
Thanks for reporting!

**Comment by Pepperoni-Jabroni** [comment]
This is fixed by a generous PR in 248e0c17ad207de74b9e68c6b78c4d4f244bb517
