### ISSUE TITLE
MapAtlases 2.2.0 + BetterNether/BetterEnd

### ISSUE THREAD

**Issue by FieryDruid** [Pepperoni-Jabroni/MapAtlases#74]
Hi, i'm playing with this mods on my local server. After updating MapAtlases on version `v2.2.0` from `v2.1.0`  it broke something in BetterNether `v7.1.1`  and BetterEnd `v2.1.1` mods. All blocks changes on other, but works correctly with MapAtlases `v2.1.0` which is why I decided to write about it here.

Perhaps you have any ideas what can be done about it?

**Comment by Pepperoni-Jabroni** [comment]
Thanks for reporting! I'll take a look.

**Comment by FieryDruid** [comment]
Works on version `2.3.0`, thanks!
