### ISSUE TITLE
[1.19.3] Crash while starting up the game

### ISSUE THREAD

**Issue by robertdomonkos82** [Pepperoni-Jabroni/MapAtlases#86]
The game simply won't start up with this mod and crashes with this error:
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'map_atlases'!
Exit Code: -1
Full crash report: <a href="https://pastebin.com/4yRWJM6c">https://pastebin.com/4yRWJM6c</a>

**Comment by Pepperoni-Jabroni** [comment]
Working on it

**Comment by Pepperoni-Jabroni** [comment]
Yeah the current v2.3.1 should be marked for 1.19-1.19.2 because 1.19.3's internals are wildly different. Working on compiling a 1.19.3 version now

**Comment by Pepperoni-Jabroni** [comment]
Published the 1.19.3 build. Thanks for reporting!
