### ISSUE TITLE
[Question] About 1.20 update

### ISSUE THREAD

**Issue by vico93** [Pepperoni-Jabroni/MapAtlases#97]
Sorry to sound annoying with this kind of question, but did you have plans to update MapAtlases to at least one of the 1.20 pre versions to "spice up" things in preparation for the full release?

**Comment by Pepperoni-Jabroni** [comment]
Port is done!

**Comment by vico93** [comment]
> Port is done!

AAAAAAAAAAAAAAA THANK YOU SO MUCH!!!

My life on Minecraft was so miserable without this mod!

**Comment by Pepperoni-Jabroni** [comment]
Thanks for the kind words! Please let me know if you have any issues or suggestions. Thanks for playing with Map Atlases!
